"""empty message

Revision ID: 94f462c5031a
Revises: ba741f11e4ad
Create Date: 2026-06-17 13:59:52.925166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f462c5031a'
down_revision = 'ba741f11e4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_subscription_user_id'))
        batch_op.create_index(batch_op.f('ix_subscription_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_business_id'), ['business_id'], unique=True)
        batch_op.create_foreign_key(None, 'business', ['business_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_subscription_business_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_user_id'))
        batch_op.create_index(batch_op.f('ix_subscription_user_id'), ['user_id'], unique=True)
        batch_op.drop_column('business_id')

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('verified')
        batch_op.drop_column('proof_url')

    # ### end Alembic commands ###
