"""empty message

Revision ID: ba741f11e4ad
Revises: 
Create Date: 2026-06-17 08:10:57.752229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba741f11e4ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('birthdate', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('account_type', sa.String(length=20), server_default='person', nullable=False),
    sa.Column('homebase', sa.String(length=120), nullable=True),
    sa.Column('professional_email', sa.String(length=120), nullable=True),
    sa.Column('premium_coins', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_owner_id'), ['owner_id'], unique=False)

    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'refused')", name='ck_friendship_status'),
    sa.CheckConstraint('requester_id <> addressee_id', name='ck_friendship_not_self'),
    sa.ForeignKeyConstraint(['addressee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendship_addressee_id'), ['addressee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendship_requester_id'), ['requester_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type IN ('friend_request', 'event_invite', 'invite_suggestion', 'event_public', 'friend_accepted', 'event_updated', 'event_cancelled', 'event_removed', 'rsvp_changed', 'suggestion_approved', 'suggestion_refused', 'event_reminder', 'event_confirmation')", name='ck_notification_type'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notification_user_read', ['user_id', 'is_read'], unique=False)

    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='incomplete', nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('provider_customer_id', sa.String(length=120), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_user_id'), ['user_id'], unique=True)

    op.create_table('business_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_post_business_id'), ['business_id'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('happened', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(business_id IS NOT NULL) <> (target_user_id IS NOT NULL)', name='ck_follow_one_target'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'business_id', name='uq_follow_business'),
    sa.UniqueConstraint('follower_id', 'target_user_id', name='uq_follow_user')
    )
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_follower_id'), ['follower_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'author_id', name='uq_review_author')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_business_id'), ['business_id'], unique=False)

    op.create_table('chat_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_a_id', sa.Integer(), nullable=True),
    sa.Column('user_b_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type IN ('event', 'dm')", name='ck_chat_room_type'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_a_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='uq_chat_room_dm_pair')
    )
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_room_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_chat_room_user_a_id'), ['user_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_room_user_b_id'), ['user_b_id'], unique=False)

    op.create_table('event_invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_invitation_pair')
    )
    with op.batch_alter_table('event_invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_invitation_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_invitation_user_id'), ['user_id'], unique=False)

    op.create_table('event_opinion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_opinion_rating_range'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'event_id', name='uq_opinion_author_event')
    )
    with op.batch_alter_table('event_opinion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_opinion_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_opinion_event_id'), ['event_id'], unique=False)

    op.create_table('event_participants',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rsvp', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.create_table('invite_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('suggested_user_id', sa.Integer(), nullable=False),
    sa.Column('suggested_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['suggested_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['suggested_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'suggested_user_id', name='uq_invite_suggestion_pair')
    )
    with op.batch_alter_table('invite_suggestion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_suggestion_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_suggestion_suggested_by_id'), ['suggested_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_suggestion_suggested_user_id'), ['suggested_user_id'], unique=False)

    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("media_type IS NULL OR media_type IN ('image', 'audio')", name='ck_chat_message_media_type'),
    sa.CheckConstraint('deleted = TRUE OR (text IS NOT NULL) OR (media_url IS NOT NULL)', name='ck_chat_message_payload'),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_room_id'), ['room_id'], unique=False)

    op.create_table('chat_room_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_chat_room_membership_pair')
    )
    with op.batch_alter_table('chat_room_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_room_membership_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_room_membership_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_room_membership_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_room_membership_room_id'))

    op.drop_table('chat_room_membership')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_room_id'))

    op.drop_table('chat_message')
    with op.batch_alter_table('invite_suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_suggestion_suggested_user_id'))
        batch_op.drop_index(batch_op.f('ix_invite_suggestion_suggested_by_id'))
        batch_op.drop_index(batch_op.f('ix_invite_suggestion_event_id'))

    op.drop_table('invite_suggestion')
    op.drop_table('event_participants')
    with op.batch_alter_table('event_opinion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_opinion_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_opinion_author_id'))

    op.drop_table('event_opinion')
    with op.batch_alter_table('event_invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_invitation_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_invitation_event_id'))

    op.drop_table('event_invitation')
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_room_user_b_id'))
        batch_op.drop_index(batch_op.f('ix_chat_room_user_a_id'))
        batch_op.drop_index(batch_op.f('ix_chat_room_event_id'))

    op.drop_table('chat_room')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_business_id'))
        batch_op.drop_index(batch_op.f('ix_review_author_id'))

    op.drop_table('review')
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_follow_follower_id'))
        batch_op.drop_index(batch_op.f('ix_follow_business_id'))

    op.drop_table('follow')
    op.drop_table('event')
    with op.batch_alter_table('business_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_post_business_id'))

    op.drop_table('business_post')
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_user_id'))

    op.drop_table('subscription')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user_read')
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))

    op.drop_table('notification')
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendship_requester_id'))
        batch_op.drop_index(batch_op.f('ix_friendship_addressee_id'))

    op.drop_table('friendship')
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_owner_id'))

    op.drop_table('business')
    op.drop_table('user')
    # ### end Alembic commands ###
