"""empty message

Revision ID: d537da61f874
Revises: 212521cb3742
Create Date: 2026-07-09 11:20:08.483732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd537da61f874'
down_revision = '212521cb3742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exp_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('peer_user_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('owner_business_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['owner_business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['peer_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exp_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exp_ledger_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exp_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exp_ledger_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exp_ledger_owner_business_id'), ['owner_business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exp_ledger_peer_user_id'), ['peer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exp_ledger_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')

    with op.batch_alter_table('exp_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exp_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_exp_ledger_peer_user_id'))
        batch_op.drop_index(batch_op.f('ix_exp_ledger_owner_business_id'))
        batch_op.drop_index(batch_op.f('ix_exp_ledger_event_id'))
        batch_op.drop_index(batch_op.f('ix_exp_ledger_created_at'))
        batch_op.drop_index(batch_op.f('ix_exp_ledger_business_id'))

    op.drop_table('exp_ledger')
    # ### end Alembic commands ###
