"""empty message

Revision ID: d91ed58785ab
Revises: 9fbc966e1709
Create Date: 2026-06-18 12:14:26.658612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91ed58785ab'
down_revision = '9fbc966e1709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='viewer', nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('invited_username', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('team_invite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invite_business_id'), ['business_id'], unique=False)

    op.create_table('team_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='viewer', nullable=False),
    sa.Column('can_manage_managers', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'user_id', name='uq_team_membership_biz_user')
    )
    with op.batch_alter_table('team_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_membership_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_membership_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_delete_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pending_delete_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['pending_delete_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pending_delete_at')
        batch_op.drop_column('pending_delete_by')

    with op.batch_alter_table('team_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_membership_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_membership_business_id'))

    op.drop_table('team_membership')
    with op.batch_alter_table('team_invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invite_business_id'))

    op.drop_table('team_invite')
    # ### end Alembic commands ###
